name: "Scratch Org Recycler - User Triggered"

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username of the scratch org"
        required: true

env:
  SFPOWERSCRIPTS_DATADOG: "true"
  SFPOWERSCRIPTS_DATADOG_HOST: "${{ vars.DATADOG_HOST }}"
  SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

jobs:
  delete-scratchorg:
    name: "Return a used scratch org to the pool ${{ github.event.inputs.username }}"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts

    steps:
      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: "Delete scratch org ${{ github.event.inputs.username }}"
        run: "sfdx sfpowerscripts:pool:org:delete -u ${{ github.event.inputs.username }} -v devhub"
