name: "CD Pipeline - User Triggered"

on:
  push:
    branches:
      - release/**
  workflow_dispatch:
    inputs:
      release-def-path:
        description: "Path to release definition file"
        required: false

jobs:
  release:
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub

      - name: "Promote package"
        run: |
          sfp orchestrator:promote -d softforce/core -v devhub
