name: "PR Validation - Auto Triggered"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

  workflow_dispatch:

env:
  SFPOWERSCRIPTS_DATADOG: "true"
  SFPOWERSCRIPTS_DATADOG_HOST: "${{ vars.DATADOG_HOST }}"
  SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

jobs:
  validate:
    name: "Validate Changed Packages"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts:latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub

      - name: "Create scratch org"
        run: |
          sf org create scratch -a org -f config/project-scratch-def.json -v devhub -y 1 -w 20
          EXEC_USER=$(sf org display user --json | jq -r .result.username)

      # Validate source and trigger test
      - name: "Push source to scratch org"
        run: sf deploy metadata -o org
